In [ ]:
!pip install numpy, pandas

In [1]:
import numpy as np

In [4]:
# Генерация массива с случайными целочислеными значениями
# Одно случайное значение из диапозона от 0 до 10
 # Скалярное значение
np.random.randint(10)

2

In [8]:
np.random.randint(10, 20, size=5)

array([19, 14, 13, 19, 12])

In [6]:
# Одномерный массив со случайными целыми значениями
np.random.randint(10, size=5)

array([6, 9, 7, 3, 3])

In [7]:
np.random.randint(5, 10, size=5)

array([8, 9, 9, 9, 7])

In [9]:
# Двумерный массив
np.random.randint(10, size=(3,5))

array([[9, 5, 4, 3, 2],
       [2, 5, 0, 2, 4],
       [2, 9, 4, 1, 4]])

* Атрибуты

In [11]:
arr_1 = np.random.randint(10, size=(3,5))
arr_1

array([[8, 4, 1, 2, 0],
       [6, 9, 0, 6, 1],
       [4, 5, 8, 0, 7]])

In [12]:
# Мерность массива(количество измерений либо осей)
arr_1.ndim

2

In [13]:
# Форма массива
arr_1.shape

(3, 5)

In [14]:
arr_1.shape[0]

3

In [15]:
# Колличество всех элементов массива
arr_1.size

15

In [16]:
# Тип данных содержащихся в масиве
# Хранит только один тип данных
arr_1.dtype

dtype('int32')

In [17]:
np.random.random(5).dtype

dtype('float64')

In [18]:
arr_1.astype("uint8")

array([[8, 4, 1, 2, 0],
       [6, 9, 0, 6, 1],
       [4, 5, 8, 0, 7]], dtype=uint8)

* Индексация

In [20]:
arr_2 = np.random.randint(10, size=10)
arr_2

array([7, 8, 3, 9, 1, 7, 1, 3, 9, 4])

In [21]:
# Прямая индексация
arr_2[0]

7

In [22]:
# Обратная индексация
arr_2[-1]

4

In [23]:
# Индексация двумерных масивов
arr_3 = np.random.randint(10, size=(3,4))
arr_3

array([[0, 4, 2, 8],
       [8, 9, 0, 5],
       [3, 7, 3, 9]])

In [29]:
# Обычный синтаксис
arr_3[1][2]

0

In [28]:
# Синтаксис NumPy
arr_3[1,2]

0

* Срезы

In [30]:
# Одномерный массив
arr_2[:5]

array([7, 8, 3, 9, 1])

In [34]:
arr_2[::-5]

array([4, 1])

In [35]:
arr_2[-2:-6:-1]

array([9, 3, 1, 7])

In [36]:
# Двумерный массив
arr_3[1:, :3]

array([[8, 9, 0],
       [3, 7, 3]])

In [37]:
arr_3[0,1:]

array([4, 2, 8])

In [38]:
arr_3[:2, 1]

array([4, 9])

* Представления(views) и копии(copies)

In [40]:
# Срез списка создает копию
my_list = [1,2,3,4,5]
sub_list = my_list[2:]
sub_list

[3, 4, 5]

In [41]:
sub_list[0] = 100
sub_list

[100, 4, 5]

In [42]:
my_list

[1, 2, 3, 4, 5]

In [44]:
# Срез массива создает представление исходного массива
my_arr = np.array([1,2,3,4,5])
sub_arr = my_arr[2:]
sub_arr

array([3, 4, 5])

In [45]:
sub_arr[0] = 10
sub_arr

array([10,  4,  5])

In [46]:
my_arr

array([ 1,  2, 10,  4,  5])

In [47]:
copy_arr = my_arr[2:].copy()
copy_arr

array([10,  4,  5])

In [48]:
copy_arr[0] = 1000
copy_arr

array([1000,    4,    5])

In [49]:
my_arr

array([ 1,  2, 10,  4,  5])

* Изменения формы

In [50]:
# Одномерный массив(вектор строка)
arr_4 = np.arange(1, 10)
arr_4

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
arr_4.shape

(9,)

In [52]:
# вЕКТОР СТОЛБЕЦ
# Технически это двухмерный массив
arr_4.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [54]:
arr_5 = np.random.random((2,3))
arr_5

array([[0.07930717, 0.75640305, 0.51210538],
       [0.50475106, 0.4036277 , 0.58653805]])

In [55]:
arr_5.reshape((3,2))

array([[0.07930717, 0.75640305],
       [0.51210538, 0.50475106],
       [0.4036277 , 0.58653805]])

In [58]:
arr_5.reshape((6,1))

array([[0.07930717],
       [0.75640305],
       [0.51210538],
       [0.50475106],
       [0.4036277 ],
       [0.58653805]])

## Операции
- универсальные функции

In [60]:
a = np.arange(5)
b = np.arange(1,6)

print(a)
print(b)

[0 1 2 3 4]
[1 2 3 4 5]


In [61]:
# Поэлементное сложение массивов
# "+" Алиас универсальной функции np.add()
a + b

array([1, 3, 5, 7, 9])

In [62]:
np.add(a, b)

array([1, 3, 5, 7, 9])

In [63]:
np.add(10, 20)

30

In [64]:
# Поэлементное умножение(Произведение Адамара)
a * b

array([ 0,  2,  6, 12, 20])

In [66]:
# Матричное умножение
c = b.reshape((5,1))
c

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [67]:
np.dot(a,c)

array([40])

In [ ]:
# a[0] * c[0] + a[1] *c[1] + a[2] * c[2] + ...